### ISSUE TITLE
Not been able to upload

### ISSUE THREAD

**Issue by outdatedx** [jeanbmar/payload-s3-upload#5]
Hey,
So I had my s3 configured and I never change the config neither for payload nor s3 but someone how the plugin has stopped working yesterday I spent almost 4 hours and was not able to figure out why Im not able to upload,

PROBLEM: (TLDR)
When I upload from my payload deploy its takes a while and never uploads it to the s3 folder.

I can add you to the repo cause I don't want to make things public and leaks something.

**Comment by jeanbmar** [comment]
Hello @outdatedx, can you please provide:
- The versions of Payload and this plugin you are using
- Some error logs or, better, a minimal reproducible example

**Comment by outdatedx** [comment]
> Hello @outdatedx, can you please provide:
> 
> - The versions of Payload and this plugin you are using
> 
> - Some error logs or, better, a minimal reproducible example
> 
> 
> 
> 

Hey, 
So I'm using Payload version 0.18.1

And that's the thing there are no logs, when I upload the upload is successful but never shows up on my s3 bucket.

**Comment by outdatedx** [comment]
// Media.ts
```js
import { CollectionConfig } from 'payload/types';
export type MediaType = {
  filename: string;
  width: number;
  height: number;
  alt: string;
  url: string;
  sizes: {
    card?: {
      filename: string;
      width: number;
      height: number;
    };
    feature?: {
      filename: string;
      width: number;
      height: number;
      url: string;
    };
  };
};

const Media: CollectionConfig = {
  slug: 'media',
  labels: {
    singular: 'Media',
    plural: 'Media',
  },
  access: {
    read: (): boolean => true, // Everyone can read Media
  },
  upload: {
    staticDir: 'media',
    staticURL: '/media',
    disableLocalStorage: true,
    // s3: {
    //   bucket: process.env.AWS_BUCKET_NAME,
    //   prefix: 'fabricstudio/assets',
    //   commandInput: {
    //     ACL: 'public-read',
    //   },
    // },
    imageSizes: [
      {
        name: 'card',
        width: 640,
        height: 480,
        crop: 'center',
      },
      {
        name: 'feature',
        width: 1024,
        height: 576,
        crop: 'center',
      },
    ],
    adminThumbnail: 'feature',
    mimeTypes: ['image/*'],
  },
  hooks: {
    afterRead: [
      ({ doc }) => {
        doc.url = `https://${process.env.AMAZONWS_BUCKET_NAME}.s3.${process.env.AMAZON_WS_REGION}.amazonaws.com/outdated/assets/${doc.filename}`;
        Object.keys(doc.sizes).forEach(
          (k) =>
            (doc.sizes[
              k
            ].url = `https://${process.env.AMAZONWS_BUCKET_NAME}.s3.${process.env.AMAZON_WS_REGION}.amazonaws.com/outdated/assets/${doc.sizes[k].filename}`)
        );
      },
    ],
  },
  fields: [
    {
      name: 'alt',
      label: 'Alt Text',
      type: 'text',
      required: true,
    },
    {
      name: 'url',
      type: 'text',
      access: {
        create: () => false,
      },
      admin: {
        disabled: true,
      },
      hooks: {
        afterRead: [
          ({ data: doc }) =>
            `https://${process.env.AMAZONWS_BUCKET_NAME}.s3.${process.env.AMAZON_WS_REGION}.amazonaws.com/outdated/assets/${doc.filename}`,
        ],
      },
    },
  ],
};

export default Media;
```

**Comment by outdatedx** [comment]
> The s3 key in the upload collection is commented. Have you applied the idea from #3? Because what jmikrut suggests is not how this plugin works. The collection-related config cannot be passed in plugin init, and I'm strongly against it. It's just bad to manage some collection config at 2 different places.
> 
> If you want to get rid of the TS warning, you need to define a custom CollectionConfig type that will allow the s3 key in the upload property.
Right that does make sense.

I did try to do it thats why is actually commented out cause I do pass the options in the config but the as you said I have to define a type so I did try to extend the CollectionConfig but it didnt work if you can help me with it that would be great

**Comment by outdatedx** [comment]
Well I think I figured it out thanks.
